# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cbda0f04573768e8e4313a2c5403380285cbf6d6f5f46601b2faea19e5341d2f34e90c5a9dc88b54d45519b4a062554875f6d7fa9799fe5621557a26422bcd7

test:
  secret_key_base: 70c57d8cb24500a3ffe072e6d01f58fdbec06ae61af500bb107de5f7e445f75cd04b0902443cb0f3151c17143edfc15240b61ad7a0695cbe5a90a982f478ce55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
